# netlify.toml - Netlify Configuration for Trip Planner PWA

[build]
  # No build process needed - static files only
  publish = "."
  
[build.environment]
  # Node version (not used but good to specify)
  NODE_VERSION = "18"

# Custom headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # PWA headers
    X-UA-Compatible = "IE=edge"
    
    # Performance headers  
    X-DNS-Prefetch-Control = "on"

# Service Worker - no cache to ensure updates
[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
    Content-Type = "application/javascript"

# Manifest file - no cache to ensure updates
[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
    Content-Type = "application/manifest+json"

# Static assets - long cache
[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "text/css"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "application/javascript"

# Images - long cache  
[[headers]]
  for = "/assets/*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "image/png"

[[headers]]
  for = "/assets/*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "image/jpeg"

[[headers]]
  for = "/assets/*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "image/svg+xml"

# Fonts
[[headers]]
  for = "/*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "font/woff2"

# API routes (if you add backend later)
[[headers]]
  for = "/api/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

# Redirects for SPA routing
[[redirects]]
  from = "/share/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["admin"]}

# Error pages
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404

# Forms (if you add contact/feedback forms later)
# Uncomment if needed:
# [[forms]]
#   name = "feedback"
#   action = "/thank-you"
#   fields = ["name", "email", "message"]

# Functions (if you add serverless functions later)
[functions]
  directory = "netlify/functions"

# Deploy previews settings
[context.deploy-preview]
  command = "echo 'No build needed for static site'"

[context.branch-deploy]
  command = "echo 'No build needed for static site'"

# Production optimizations
[context.production]
  [context.production.environment]
    NODE_ENV = "production"

# Plugin settings (optional optimizations)
[[plugins]]
  package = "@netlify/plugin-sitemap"

# Performance optimizations
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = false
  minify = true

[build.processing.js]
  bundle = false
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true

# Edge functions (if you need them later)
# [[edge_functions]]
#   function = "geolocation"
#   path = "/api/location"
